from __future__ import annotations

import json
from itertools import count
import re
from urllib import error, request

from app.infrastructure.llm.json_content import parse_json_content
from app.simulation.planner import AbstractStoryPlanner
from app.simulation.protocol import CapabilitySpec, StoryPlan, StoryStep


class SiliconFlowStoryPlanner(AbstractStoryPlanner):
    def __init__(
        self,
        *,
        api_key: str,
        model_name: str,
        base_url: str,
        max_attempts: int = 3,
    ) -> None:
        self.api_key = api_key
        self.model_name = model_name
        self.base_url = base_url.rstrip("/")
        self.max_attempts = max(1, max_attempts)
        self._story_counter = count(1)

    def build_story_plan(
        self,
        *,
        goal: str,
        actors: list[str],
        capabilities: list[CapabilitySpec],
    ) -> StoryPlan:
        payload = self._build_payload(goal=goal, actors=actors, capabilities=capabilities)
        parsed: dict | None = None
        last_error = "unknown error"
        needs_strict_reference_fix = False
        for _attempt in range(1, self.max_attempts + 1):
            if needs_strict_reference_fix:
                payload["messages"].append(
                    {
                        "role": "user",
                        "content": (
                            "Your previous JSON used invalid or fragile references. "
                            "Rewrite with concrete executable references only, such as '$step_1.output.threads[0].id'. "
                            "Never use '[?]', '<index>', 'latest', or references that depend on possibly empty arrays. "
                            "For forum publishing goals, avoid read_thread steps unless the thread ID is guaranteed from a previous create_thread step."
                        ),
                    }
                )

            parsed, error_reason = self._call_model(payload)
            if parsed is None:
                last_error = error_reason or "invalid or empty planner response"
                continue

            if self._has_invalid_references(parsed):
                needs_strict_reference_fix = True
                last_error = "planner returned invalid reference placeholders"
                continue

            steps = self._build_steps(parsed, actors)
            if not steps:
                last_error = "planner returned no usable steps"
                continue

            if self._steps_have_invalid_references(steps):
                needs_strict_reference_fix = True
                last_error = "planner steps still contain invalid references"
                continue

            if self._steps_are_fragile(steps):
                needs_strict_reference_fix = True
                last_error = "planner returned fragile references (possibly empty board thread list)"
                continue

            story_id = str(parsed.get("story_id", f"sf-story-{next(self._story_counter):04d}"))
            return StoryPlan(
                story_id=story_id,
                goal=goal,
                steps=steps,
                planner_name="siliconflow",
                planner_source=f"remote_llm:{self.model_name}",
                fallback_used=False,
                planner_detail="Plan generated by SiliconFlow remote planner.",
            )

        raise RuntimeError(
            f"SiliconFlow planner failed after {self.max_attempts} attempts: {last_error}"
        )

    def _build_steps(self, parsed: dict, actors: list[str]) -> list[StoryStep]:
        steps_data = parsed.get("steps", [])
        steps: list[StoryStep] = []
        for index, item in enumerate(steps_data, start=1):
            capability = str(item.get("capability", "")).strip()
            actor_id = str(item.get("actor_id", actors[0] if actors else "aria")).strip()
            payload_data = item.get("payload", {})
            depends_on = item.get("depends_on", [])
            rationale = str(item.get("rationale", "")).strip()
            if not capability or not isinstance(payload_data, dict):
                continue
            if not isinstance(depends_on, list):
                depends_on = []
            steps.append(
                StoryStep(
                    step_id=str(item.get("step_id", f"step-{index}")),
                    capability=capability,
                    actor_id=actor_id,
                    payload=payload_data,
                    depends_on=[str(dep) for dep in depends_on],
                    rationale=rationale,
                )
            )
        return steps

    def _build_payload(self, *, goal: str, actors: list[str], capabilities: list[CapabilitySpec]) -> dict:
        capability_lines = []
        for item in capabilities:
            capability_lines.append(
                {
                    "name": item.name,
                    "site": item.site,
                    "description": item.description,
                    "read_only": item.read_only,
                    "input_schema": item.input_schema,
                }
            )

        system_prompt = (
            "You are a story planner for a multi-site AI society simulation. "
            "Return ONLY JSON with fields: story_id, steps[]. "
            "Each step must include: step_id, capability, actor_id, payload, depends_on, rationale. "
            "Only use provided capabilities. Ensure causality and cross-site consistency. "
            "If an input_schema includes allowed_* values, you MUST use one of those exact values. "
            "Do not invent board slugs, thread ids, site ids, or capability names. "
            "When a later step needs an object from an earlier step, reference it explicitly using '$step_id.output.field' syntax. "
            "Example: use '$step_1.output.threads[0].id' or '$step_2.output.thread_id' instead of invented placeholders. "
            "For publishable text fields such as title/content, always use English text. "
            "For any publishable text such as title/content, write the final in-world forum text directly. "
            "Do not include prompt language like '生成一个', '请生成', '你是', '输出JSON', or any meta instructions in the content fields."
        )

        user_prompt = {
            "goal": goal,
            "actors": actors,
            "capabilities": capability_lines,
        }

        return {
            "model": self.model_name,
            "temperature": 0.2,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": json.dumps(user_prompt, ensure_ascii=True)},
            ],
            "response_format": {"type": "json_object"},
        }

    def _call_model(self, payload: dict) -> tuple[dict | None, str | None]:
        endpoint = f"{self.base_url}/chat/completions"
        body = json.dumps(payload).encode("utf-8")
        http_request = request.Request(
            endpoint,
            data=body,
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )

        try:
            with request.urlopen(http_request, timeout=30) as response:
                response_text = response.read().decode("utf-8")
        except TimeoutError:
            return None, "timeout"
        except error.HTTPError as exc:
            try:
                body_preview = exc.read().decode("utf-8", errors="replace")[:400]
            except Exception:
                body_preview = "<unavailable>"
            return None, f"http {exc.code}: {body_preview}"
        except error.URLError as exc:
            return None, f"url_error: {exc.reason}"

        try:
            data = json.loads(response_text)
            content = data["choices"][0]["message"]["content"]
            parsed = parse_json_content(content)
            if parsed is None:
                return None, "content_json_parse_failed"
            return parsed, None
        except (KeyError, IndexError, TypeError, ValueError, json.JSONDecodeError) as exc:
            return None, f"response_parse_error: {exc}"

    def _has_invalid_references(self, parsed: dict) -> bool:
        steps = parsed.get("steps", [])
        if not isinstance(steps, list):
            return True
        for item in steps:
            payload = item.get("payload", {}) if isinstance(item, dict) else {}
            if self._payload_has_invalid_reference(payload):
                return True
        return False

    def _steps_have_invalid_references(self, steps: list[StoryStep]) -> bool:
        return any(self._payload_has_invalid_reference(step.payload) for step in steps)

    def _steps_are_fragile(self, steps: list[StoryStep]) -> bool:
        step_capabilities = {step.step_id: step.capability for step in steps}

        def uses_board_thread_reference(payload: dict) -> bool:
            for value in payload.values():
                if isinstance(value, dict) and uses_board_thread_reference(value):
                    return True
                if isinstance(value, list):
                    if any(isinstance(item, dict) and uses_board_thread_reference(item) for item in value):
                        return True
                    if any(isinstance(item, str) and self._is_board_thread_reference(item, step_capabilities) for item in value):
                        return True
                if isinstance(value, str) and self._is_board_thread_reference(value, step_capabilities):
                    return True
            return False

        return any(uses_board_thread_reference(step.payload) for step in steps)

    def _is_board_thread_reference(self, value: str, step_capabilities: dict[str, str]) -> bool:
        match = re.search(r"\$?(step[_-]\d+)\.output\.threads\[(\d+)\]\.id", value)
        if not match:
            return False
        referenced_step = match.group(1)
        return step_capabilities.get(referenced_step) == "forum.read_board"

    def _payload_has_invalid_reference(self, payload: dict) -> bool:
        placeholder_patterns = [
            re.compile(r"\[\?\]"),
            re.compile(r"<index>", re.IGNORECASE),
            re.compile(r"\$step[_-]\d+\.output\.[^\s]*latest", re.IGNORECASE),
        ]

        def contains_invalid(value) -> bool:
            if isinstance(value, dict):
                return any(contains_invalid(item) for item in value.values())
            if isinstance(value, list):
                return any(contains_invalid(item) for item in value)
            if not isinstance(value, str):
                return False
            return any(pattern.search(value) for pattern in placeholder_patterns)

        return contains_invalid(payload)
