<script setup>
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
  <div class="nd-shell">
    <header class="nd-header">
      <div class="nd-header__top">
        <span class="nd-logo">■ GreenLeaf Archive</span>
        <span class="nd-tagline">Distributed document relay — read-only public access</span>
      </div>
      <nav class="nd-nav">
        <RouterLink to="/netdisk" class="nd-nav__link">File Archive</RouterLink>
        <RouterLink to="/news" class="nd-nav__link">GreenLeaf News</RouterLink>
        <RouterLink to="/forum" class="nd-nav__link nd-nav__link--alt">↩ Back to Forum</RouterLink>
      </nav>
    </header>

    <main class="nd-main">
      <RouterView />
    </main>

    <footer class="nd-footer">
      GreenLeaf Archive — read-only public mirror — files generated by registered operators
    </footer>
  </div>
</template>

<style scoped>
*,
*::before,
*::after {
  box-sizing: border-box;
}

.nd-shell {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background: #e8f5e9;
  color: #1b3a1f;
  font-family: 'Courier New', Courier, monospace;
}

.nd-header {
  background: #2e7d32;
  color: #c8e6c9;
  border-bottom: 3px solid #1b5e20;
}

.nd-header__top {
  display: flex;
  align-items: baseline;
  gap: 1.4rem;
  padding: 0.7rem 1.2rem 0.5rem;
  flex-wrap: wrap;
}

.nd-logo {
  font-size: 1.15rem;
  font-weight: 700;
  letter-spacing: 0.06em;
  color: #a5d6a7;
}

.nd-tagline {
  font-size: 0.78rem;
  color: #81c784;
  opacity: 0.9;
}

.nd-nav {
  display: flex;
  gap: 0;
  border-top: 1px solid #1b5e20;
}

.nd-nav__link {
  display: inline-block;
  padding: 0.42rem 1.1rem;
  color: #c8e6c9;
  text-decoration: none;
  font-size: 0.83rem;
  font-weight: 700;
  border-right: 1px solid #1b5e20;
  transition: background 0.15s;
}

.nd-nav__link:hover,
.nd-nav__link.router-link-active {
  background: #1b5e20;
  color: #e8f5e9;
}

.nd-nav__link--alt {
  color: #a5d6a7;
}

.nd-main {
  flex: 1;
  padding: 1.4rem 1.2rem;
}

.nd-footer {
  background: #1b5e20;
  color: #a5d6a7;
  text-align: center;
  font-size: 0.76rem;
  padding: 0.55rem;
  letter-spacing: 0.04em;
}
</style>
